import { Pipe, PipeTransform } from '@angular/core';

const translations: Record<string, string> = {
  'app.civilDefense': 'الدفاع المدني',
  'app.dashboard': 'الرئيسية',
  'app.activityTypes': 'أنواع الأنشطة',
  'app.requestingEntities': 'الجهات الطالبة',
  'app.districts': 'الأحياء',
  'app.shopLicenses': 'تراخيص المحال',
  'app.allProcesses': 'جميع المعاملات',
  'app.inspections': 'المعاينات',
  'app.finalApproval': 'الاعتماد النهائي',
  'app.archive': 'الأرشيف',
  'app.licenses': 'طلبات الترخيص',
  'app.logout': 'تسجيل الخروج',
  'app.greeting': 'مرحبًا بك',

  'common.systemManagement': 'إدارة النظام',
  'common.requestCode': 'رقم الطلب',
  'common.code': 'الكود',
  'common.name': 'الاسم',
  'common.actions': 'الإجراءات',
  'common.options': 'خيارات',
  'common.close': 'إغلاق',
  'common.cancel': 'إلغاء',
  'common.clear': 'مسح',
  'common.edit': 'تعديل',
  'common.delete': 'حذف',
  'common.deleting': 'جارٍ الحذف...',
  'common.confirmDelete': 'تأكيد الحذف',
  'common.saving': 'جارٍ الحفظ...',
  'common.save': 'حفظ',
  'common.saveEdit': 'حفظ التعديلات',
  'common.refresh': 'تحديث',
  'common.search': 'بحث',
  'common.reset': 'إعادة تعيين',
  'common.loadingDataWithEllipsis': 'جارٍ تحميل البيانات...',
  'common.loadingDetails': 'جارٍ تحميل التفاصيل...',
  'common.empty': 'لا توجد بيانات',
  'common.actionConfirmation': 'تأكيد الإجراء',
  'common.submissionDate': 'تاريخ التقديم',
  'common.createdBy': 'أُنشئ بواسطة',
  'common.currentStep': 'المرحلة الحالية',
  'common.establishmentData': 'بيانات المنشأة',
  'common.establishment': 'المنشأة',
  'common.establishmentName': 'اسم المنشأة',
  'common.establishmentAddress': 'عنوان المنشأة',
  'common.address': 'العنوان',
  'common.entity': 'الجهة',
  'common.requestingEntity': 'الجهة الطالبة',
  'common.district': 'الحي',
  'common.activity': 'النشاط',
  'common.applicantData': 'بيانات مقدم الطلب',
  'common.applicant': 'مقدم الطلب',
  'common.applicantName': 'اسم مقدم الطلب',
  'common.applicantRole': 'صفة مقدم الطلب',
  'common.nationalId': 'الرقم القومي',
  'common.responsibleManager': 'المدير المسؤول',
  'common.phone': 'رقم الهاتف',
  'common.inspectionData': 'بيانات المعاينة',
  'common.inspector': 'المعاين',
  'common.inspectorName': 'اسم المعاين',
  'common.opinion': 'الرأي الفني',
  'common.finalApprovalData': 'بيانات الاعتماد النهائي',
  'common.finalDecisionState': 'القرار النهائي',
  'common.archivedBy': 'أُرشف بواسطة',
  'common.approvedBy': 'اعتمد بواسطة',
  'common.attachments': 'المرفقات',
  'common.noFiles': 'لا توجد ملفات',
  'common.openFile': 'فتح الملف',
  'common.notes': 'الملاحظات',
  'common.noNotes': 'لا توجد ملاحظات',
  'common.stepLabel': 'المرحلة',
  'common.contentLabel': 'المحتوى',
  'common.timeLabel': 'التاريخ والوقت',
  'common.byLabel': 'بواسطة',
  'common.returnState': 'حالة الإعادة',
  'common.receivedDate': 'تاريخ الاستلام',
  'common.decisionData': 'بيانات القرار',
  'common.yes': 'نعم',
  'common.no': 'لا',
  'common.chooseEntity': 'اختر الجهة',
  'common.chooseDistrict': 'اختر الحي',
  'common.chooseActivity': 'اختر النشاط',
  'common.dateFrom': 'من تاريخ',
  'common.dateTo': 'إلى تاريخ',
  'common.exampleCode': 'مثال: 1001',
  'common.exampleActivity': 'مثال: نشاط تجاري',
  'common.inspectionReports': 'تقارير المعاينة',
  'common.entityLetters': 'خطابات الجهة',
  'common.proofDocuments': 'مستندات الإثبات',
  'common.engineeringReports': 'التقارير الهندسية',
  'common.otherAttachments': 'مرفقات أخرى',
  'common.rejectionReason': 'سبب الرفض',
  'common.step.inspection': 'مرحلة المعاينة',

  'dashboard.welcome': 'مرحبًا {{ username }}',
  'dashboard.mainTitle': 'لوحة المعلومات',
  'dashboard.description': 'ملخص الطلبات والإجراءات في النظام',
  'dashboard.totalRequests': 'إجمالي الطلبات',
  'dashboard.underReview': 'طلبات قيد المراجعة',
  'dashboard.completedInspections': 'المعاينات المكتملة',
  'dashboard.rejectedRequests': 'الطلبات المرفوضة',

  'login.title': 'منصة إدارة تراخيص المحال',
  'login.description': 'منصة موحدة لمتابعة طلبات التراخيص والمعاينات والاعتمادات.',
  'login.requests': 'الطلبات',
  'login.registrationTracking': 'تسجيل الطلبات ومتابعتها',
  'login.inspections': 'المعاينات',
  'login.reportsNotes': 'التقارير والملاحظات الفنية',
  'login.archive': 'الأرشيف',
  'login.quickReturn': 'الوصول السريع إلى الطلبات السابقة',
  'login.loginLabel': 'تسجيل الدخول',
  'login.heading': 'مرحبًا بعودتك',
  'login.prompt': 'أدخل بياناتك للمتابعة إلى النظام.',
  'login.username': 'اسم المستخدم',
  'login.usernamePlaceholder': 'أدخل اسم المستخدم',
  'login.usernameRequired': 'اسم المستخدم مطلوب',
  'login.password': 'كلمة المرور',
  'login.passwordPlaceholder': 'أدخل كلمة المرور',
  'login.passwordRequired': 'كلمة المرور مطلوبة',
  'login.hidePassword': 'إخفاء كلمة المرور',
  'login.showPassword': 'إظهار كلمة المرور',
  'login.submit': 'دخول',
  'login.submitting': 'جارٍ تسجيل الدخول...',

  'entity.manage': 'إدارة الجهات الطالبة',
  'entity.description': 'إضافة الجهات الطالبة وتعديل بياناتها وإدارتها.',
  'entity.add': 'إضافة جهة',
  'entity.addNew': 'إضافة جهة جديدة',
  'entity.editDetails': 'تعديل بيانات الجهة',
  'entity.list': 'قائمة الجهات الطالبة',
  'entity.listDescription': 'عرض الجهات المسجلة وإدارة بياناتها.',
  'entity.listRegistered': 'الجهات المسجلة',
  'entity.code': 'كود الجهة',
  'entity.name': 'اسم الجهة',
  'entity.exampleCode': 'مثال: 1001',
  'entity.exampleName': 'مثال: الوحدة المحلية',
  'entity.exampleLocalUnit': 'مثال: الوحدة المحلية',
  'entity.save': 'حفظ الجهة',
  'entity.edit': 'تعديل الجهة',
  'entity.delete': 'حذف الجهة',
  'entity.deletePrompt': 'هل أنت متأكد من حذف هذه الجهة؟',
  'entity.empty': 'لا توجد جهات مسجلة',

  'activity.title': 'إدارة أنواع الأنشطة',
  'activity.manageDescription': 'إضافة أنواع الأنشطة وتعديلها وإدارتها.',
  'activity.add': 'إضافة نشاط',
  'activity.list': 'قائمة الأنشطة',
  'activity.manage': 'إدارة الأنشطة',
  'activity.edit': 'تعديل النشاط',
  'activity.delete': 'حذف النشاط',
  'activity.deletePrompt': 'هل أنت متأكد من حذف هذا النشاط؟',
  'activity.code': 'كود النشاط',
  'activity.name': 'اسم النشاط',
  'activity.save': 'حفظ النشاط',
  'activity.listDescription': 'عرض أنواع الأنشطة المسجلة وإدارتها.',
  'activity.empty': 'لا توجد أنشطة مسجلة',

  'district.manage': 'إدارة الأحياء',
  'district.description': 'إضافة الأحياء وتعديل بياناتها وإدارتها.',
  'district.add': 'إضافة حي',
  'district.addNew': 'إضافة حي جديد',
  'district.edit': 'تعديل الحي',
  'district.editName': 'تعديل بيانات الحي',
  'district.delete': 'حذف الحي',
  'district.deletePrompt': 'هل أنت متأكد من حذف هذا الحي؟',
  'district.code': 'كود الحي',
  'district.name': 'اسم الحي',
  'district.example': 'مثال: حي وسط المدينة',
  'district.save': 'حفظ الحي',
  'district.list': 'قائمة الأحياء',
  'district.listDescription': 'عرض الأحياء المسجلة وإدارة بياناتها.',
  'district.listRegistered': 'الأحياء المسجلة',
  'district.manageLabel': 'إدارة الأحياء',
  'district.empty': 'لا توجد أحياء مسجلة',

  'archive.title': 'الأرشيف',
  'archive.description': 'استعراض الطلبات المؤرشفة وبياناتها.',
  'archive.searchPlaceholder': 'ابحث في الطلبات المؤرشفة',
  'archive.reviewStatus': 'حالة المراجعة',
  'archive.all': 'الكل',
  'archive.reset': 'مسح عوامل التصفية',
  'archive.confirmDelete': 'تأكيد حذف الطلب',
  'archive.deletePrompt': 'هل أنت متأكد من حذف هذا الطلب؟',
  'archive.transactionData': 'بيانات الطلب',
  'archive.nationalId': 'الرقم القومي',
  'archive.finalStatus': 'الحالة النهائية',
  'archive.createdAt': 'تاريخ الإنشاء',
  'archive.inspectedBy': 'تمت المعاينة بواسطة',
  'archive.approvedBy': 'اعتمد الطلب بواسطة',
  'archive.archivedBy': 'أُرشف الطلب بواسطة',
  'archive.reviews': 'المراجعات',
  'archive.reviewState': 'حالة المراجعة',
  'archive.paid': 'تم السداد',
  'archive.reviewedBy': 'تمت المراجعة بواسطة',
  'archive.reviewDate': 'تاريخ المراجعة',
  'archive.list': 'الطلبات المؤرشفة',
  'archive.results': 'نتائج الأرشيف',
  'archive.totalRecords': 'إجمالي السجلات: {{ count }}',
  'archive.empty': 'لا توجد طلبات مؤرشفة',
  'archive.details': 'التفاصيل',

  'inspection.details': 'تفاصيل المعاينة',
  'inspection.loading': 'جارٍ تحميل بيانات المعاينة...',
  'inspection.returned': 'تمت الإعادة للمعاينة',
  'inspection.notReturned': 'لم تتم الإعادة',
  'inspection.process': 'إجراء المعاينة',
  'inspection.notes': 'ملاحظات المعاينة',
  'inspection.oldAttachments': 'المرفقات السابقة',
  'inspection.newData': 'بيانات المعاينة',
  'inspection.inspectorPlaceholder': 'أدخل اسم المعاين',
  'inspection.notesLabel': 'ملاحظات',
  'inspection.notePlaceholder': 'اكتب الملاحظات',
  'inspection.save': 'حفظ المعاينة',

  'final.deleteTitle': 'حذف طلب الاعتماد النهائي',
  'final.deletePrompt': 'هل أنت متأكد من حذف هذا الطلب؟',
  'final.title': 'تفاصيل الاعتماد النهائي',
  'final.loading': 'جارٍ تحميل بيانات الاعتماد...',
  'final.decision': 'قرار الاعتماد النهائي',
  'final.approve': 'مقبول',
  'final.rejectionPlaceholder': 'اكتب سبب الرفض',
  'final.saveDecision': 'حفظ القرار',
  'final.returnTitle': 'إعادة الطلب إلى المعاينة',
  'final.returnPrompt': 'هل تريد إعادة الطلب إلى مرحلة المعاينة؟',
  'final.returnReason': 'سبب الإعادة',
  'final.returnReasonPlaceholder': 'اكتب سبب إعادة الطلب',
  'final.processingReturn': 'جارٍ إعادة الطلب...',
  'final.confirmReturn': 'تأكيد الإعادة',

  'licensing.addTitle': 'إضافة طلب ترخيص',
  'licensing.addDescription': 'أدخل بيانات طلب الترخيص الجديد.',
  'licensing.loadingLists': 'جارٍ تحميل القوائم...',
  'licensing.save': 'حفظ الطلب',
  'licensing.deleteTitle': 'حذف طلب الترخيص',
  'licensing.deletePrompt': 'هل أنت متأكد من حذف طلب الترخيص؟',
  'licensing.detailsTitle': 'تفاصيل طلب الترخيص',
  'licensing.editTitle': 'تعديل طلب الترخيص',
  'licensing.editDescription': 'عدّل بيانات طلب الترخيص.',
  'licensing.managementTitle': 'إدارة طلبات الترخيص',
  'licensing.managementDescription': 'عرض طلبات الترخيص وإدارتها.',
  'licensing.addAction': 'إضافة طلب ترخيص',

  'newLicense.management': 'إدارة التراخيص',
  'newLicense.create': 'إنشاء طلب ترخيص',
  'newLicense.createFailed': 'تعذر إنشاء طلب الترخيص',
  'newLicense.createSucceeded': 'تم إنشاء طلب الترخيص بنجاح',
  'newLicense.createError': 'حدث خطأ أثناء إنشاء طلب الترخيص',
  'newLicense.moveFallbackError': 'تعذر نقل الطلب إلى مرحلة المعاينة',
  'newLicense.submissionDate': 'تاريخ تقديم الطلب',
  'newLicense.dateRequired': 'تاريخ التقديم مطلوب',
  'newLicense.dateFuture': 'لا يمكن أن يكون التاريخ في المستقبل',
  'newLicense.establishmentRequired': 'اسم المنشأة مطلوب',
  'newLicense.establishmentTooLong': 'اسم المنشأة أطول من الحد المسموح',
  'newLicense.entityRequired': 'الجهة الطالبة مطلوبة',
  'newLicense.districtRequired': 'الحي مطلوب',
  'newLicense.activityRequired': 'النشاط مطلوب',
  'newLicense.addressRequired': 'عنوان المنشأة مطلوب',
  'newLicense.addressTooLong': 'عنوان المنشأة أطول من الحد المسموح',
  'newLicense.mobile': 'رقم الهاتف المحمول',
  'newLicense.mobileRequired': 'رقم الهاتف المحمول مطلوب',
  'newLicense.mobileInvalid': 'رقم الهاتف المحمول غير صحيح',
  'newLicense.applicantRequired': 'اسم مقدم الطلب مطلوب',
  'newLicense.nameTooLong': 'الاسم أطول من الحد المسموح',
  'newLicense.roleRequired': 'صفة مقدم الطلب مطلوبة',
  'newLicense.nationalIdPlaceholder': 'أدخل الرقم القومي المكوّن من 14 رقمًا',
  'newLicense.nationalIdRequired': 'الرقم القومي مطلوب',
  'newLicense.nationalIdInvalid': 'الرقم القومي يجب أن يتكون من 14 رقمًا',
  'newLicense.responsible': 'المدير المسؤول',
  'newLicense.managerRequired': 'اسم المدير المسؤول مطلوب',
  'newLicense.attachments': 'المرفقات',
  'newLicense.remove': 'إزالة المرفق',
  'newLicense.reviewData': 'مراجعة البيانات',
  'newLicense.save': 'حفظ الطلب',
  'newLicense.saveAndInspect': 'حفظ وإرسال للمعاينة',
  'newLicense.details': 'تفاصيل طلب الترخيص',
  'newLicense.loading': 'جارٍ تحميل الطلب...',
  'newLicense.basicData': 'البيانات الأساسية',
  'newLicense.listTitle': 'طلبات الترخيص الجديدة',
  'newLicense.detailsAction': 'عرض التفاصيل',
  'newLicense.nextStep': 'المرحلة التالية',
  'newLicense.clear': 'إلغاء الطلب',
  'newLicense.empty': 'لا توجد طلبات ترخيص',
  'newLicense.searchPlaceholder': 'ابحث برقم الطلب أو اسم المنشأة',
  'newLicense.allEntities': 'كل الجهات',
  'newLicense.allDistricts': 'كل الأحياء',
  'newLicense.allActivities': 'كل الأنشطة',

  'opinion.compliant': 'مطابق',
  'opinion.nonCompliant': 'غير مطابق',
  'review.accepted': 'مقبول',
  'review.rejected': 'مرفوض',
};

const fallbackWords: Record<string, string> = {
  accepted: 'مقبول',
  action: 'إجراء',
  actions: 'الإجراءات',
  add: 'إضافة',
  all: 'كل',
  applicant: 'مقدم الطلب',
  archive: 'الأرشيف',
  archived: 'مؤرشف',
  attachment: 'مرفق',
  attachments: 'المرفقات',
  approval: 'اعتماد',
  approved: 'معتمد',
  by: 'بواسطة',
  cancel: 'إلغاء',
  clear: 'مسح',
  code: 'كود',
  completed: 'مكتمل',
  confirmation: 'تأكيد',
  count: 'عدد',
  current: 'حالي',
  data: 'بيانات',
  date: 'تاريخ',
  delete: 'حذف',
  deleting: 'جارٍ الحذف',
  description: 'الوصف',
  detail: 'تفاصيل',
  details: 'التفاصيل',
  district: 'الحي',
  districts: 'الأحياء',
  edit: 'تعديل',
  empty: 'لا توجد بيانات',
  entity: 'الجهة',
  entities: 'الجهات',
  error: 'خطأ',
  establishment: 'المنشأة',
  example: 'مثال',
  failed: 'تعذر',
  file: 'ملف',
  files: 'ملفات',
  final: 'نهائي',
  from: 'من',
  greeting: 'مرحبًا',
  id: 'رقم',
  inspection: 'المعاينة',
  inspections: 'المعاينات',
  label: 'البيان',
  list: 'قائمة',
  loading: 'جارٍ التحميل',
  manager: 'المدير',
  management: 'إدارة',
  mobile: 'الهاتف المحمول',
  name: 'الاسم',
  national: 'قومي',
  new: 'جديد',
  next: 'التالي',
  no: 'لا',
  notes: 'ملاحظات',
  number: 'رقم',
  opinion: 'الرأي',
  paid: 'مسدد',
  process: 'إجراء',
  prompt: 'تأكيد',
  received: 'مستلم',
  record: 'سجل',
  records: 'السجلات',
  refresh: 'تحديث',
  rejected: 'مرفوض',
  request: 'طلب',
  requests: 'الطلبات',
  required: 'مطلوب',
  return: 'إعادة',
  review: 'مراجعة',
  save: 'حفظ',
  saving: 'جارٍ الحفظ',
  search: 'بحث',
  state: 'حالة',
  status: 'الحالة',
  step: 'مرحلة',
  submit: 'إرسال',
  submitting: 'جارٍ الإرسال',
  title: 'العنوان',
  to: 'إلى',
  total: 'إجمالي',
  under: 'قيد',
  username: 'اسم المستخدم',
  with: '',
  yes: 'نعم',
};

function fallbackTranslation(key: string): string {
  const words = key
    .split('.')
    .slice(1)
    .join(' ')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .toLowerCase()
    .split(/\s+/);
  const translatedWords = words
    .map(word => fallbackWords[word])
    .filter((word): word is string => Boolean(word));

  return translatedWords.length ? translatedWords.join(' ') : 'نص غير متاح';
}

@Pipe({ name: 't', standalone: true })
export class TranslatePipe implements PipeTransform {
  transform(value: string | null | undefined, params?: Record<string, unknown>): string {
    if (!value) {
      return '';
    }

    const translated = translations[value] ?? fallbackTranslation(value);
    return translated.replace(/\{\{\s*(\w+)\s*\}\}/g, (_match, name: string) =>
      String(params?.[name] ?? ''),
    );
  }
}